from enum import Enum

class AX12Error(Enum):
    AX12_ERR_INPUT_VOLTAGE = 0
    AX12_ERR_ANGLE_LIMIT = 1
    AX12_ERR_OVERHEATING = 2
    AX12_ERR_RANGE = 3
    AX12_ERR_CHECKSUM = 4
    AX12_ERR_OVERLOAD = 5
    AX12_ERR_INSTRUCTION = 6
    AX12_ERR_NO_RESPONSE = 7
    AX12_ERR_INVALID_RESPONSE = 8