from enum import Enum

class AX12Error(Enum):
    AX12_ERR_INPUT_VOLTAGE = 1
    AX12_ERR_ANGLE_LIMIT = 2
    AX12_ERR_OVERHEATING = 3
    AX12_ERR_RANGE = 4
    AX12_ERR_CHECKSUM = 5
    AX12_ERR_OVERLOAD = 6
    AX12_ERR_INSTRUCTION = 7
    AX12_ERR_NO_RESPONSE = 8
    AX12_ERR_INVALID_RESPONSE = 9